# Generated by Django 2.0.4 on 2018-05-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('reviews', models.IntegerField()),
                ('grade', models.CharField(max_length=2)),
                ('noise', models.IntegerField()),
                ('price', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('picture', models.CharField(max_length=10000)),
            ],
        ),
    ]
